### ISSUE TITLE
Add a section about not hardcoding assumptions about the system

### ISSUE THREAD

**Issue by robrwo** [azet/community_bash_style_guide#9]
Don't hardcode assumptions about the system when they can be queried, e.g. don't assume a user's home directory is in /home/username. Get it by running `getent passwd username | cut -f6 -d:`.

**Comment by azet** [comment]
Would you be willing to contribute such a section in a PR? 

thanks, 
Aaron

**Comment by azet** [comment]
@robrwo any update?

**Comment by robrwo** [comment]
@azet no, I've been busy the past couple of months.

**Comment by azet** [comment]
@robrwo no worries. take your time!

**Comment by azet** [comment]
@robrwo 

As there's no progress I'm closing this for now. Feel free to open a pull request once this work has been done and reference this issue in it.

**Comment by robrwo** [comment]
I've been busy, and it's on my to-do list.

**Comment by azet** [comment]
@robrwo sure, no problem. would you like me to re-open the issue?

ideally I'd wait until there's some progress.

**Comment by robrwo** [comment]
When I have something, I'll write a pull request. But I'd leave the issue open as a reminder.

**Comment by azet** [comment]
@robrwo ping?

**Comment by robrwo** [comment]
I'm still thinking about this. Busy.

**Comment by azet** [comment]
As there has been no progress in six (6) years, with the last comment from beginning of 2017 (four years ago), I'm going ahead and will close this ticket. You may re-open it, if you think it's appropriate. Although in that case I'd prefer a pull request with suggested changes for us to review, instead of a duplicate issue.

All the best,
Aaron
